# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import moneybook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to=moneybook.models.user_path)),
                ('payment_date', models.DateTimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('etc', models.TextField(default=None)),
            ],
        ),
    ]
